name: Start a native build with EAS
description: This composite action can be used for triggering a native app build on EAS
inputs:
  platform:
    description: The platform to build (ios | android | all)
    required: true
  profile:
    description: The eas profile to build (e.g. "development")
    required: true
  EXPO_TOKEN:
    description: Token for EAS
    required: true
runs:
  using: "composite"
  steps:
    - name: 🏗 Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: "npm"

    - name: 🏗  Setup Yarn
      run: npm install --g yarn
      shell: bash

    - name: 📦  Cache dependencies
      uses: actions/cache@v3
      id: yarn-cache
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: 📦  Install Node.js dependencies
      run: yarn install --frozen-lockfile --prefer-offline
      shell: bash

    - name: 🏗  Setup EAS CLI
      uses: expo/expo-github-action@v7
      with:
        eas-version: latest
        token: ${{ inputs.EXPO_TOKEN }}

    - name: 🚀  Send build request without submit
      if: ${{ github.event.inputs.profile != 'production' }}
      run: eas build --platform ${{ inputs.platform }} --non-interactive --no-wait --profile ${{ inputs.profile }}
      shell: bash
